FROM ruby:3.3.6-slim

RUN apt-get clean all && apt-get update -qq && apt-get install -y build-essential libpq-dev \
    curl gnupg2 apt-utils default-libmysqlclient-dev git libcurl4-openssl-dev cmake \
    libssl-dev pkg-config openssl imagemagick file nodejs yarn postgresql-client ca-certificates

RUN mkdir /rails-app

WORKDIR /rails-app

RUN gem install rails

COPY Gemfile Gemfile.lock ./
RUN bundle install

# COPY . .
COPY . /rails-app

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["bin/rails", "server", "-b", "0.0.0.0"]